"""initial_schema

Revision ID: 3b3efd9fbe48
Revises:
Create Date: 2026-05-14 20:16:24.774169

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b3efd9fbe48"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hangars",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "passengers",
        sa.Column("passenger_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("national_id", sa.String(length=20), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("passenger_id"),
        sa.UniqueConstraint("national_id"),
    )
    op.create_table(
        "airplanes",
        sa.Column("plate_number", sa.String(length=20), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("last_maintenance_date", sa.Date(), nullable=False),
        sa.Column("next_maintenance_date", sa.Date(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(length=20), nullable=False),
        sa.Column("owner_name", sa.String(length=100), nullable=False),
        sa.Column("hangar_id", sa.String(length=20), nullable=False),
        sa.Column("fuel_capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hangar_id"],
            ["hangars.id"],
        ),
        sa.PrimaryKeyConstraint("plate_number"),
    )
    op.create_table(
        "flights",
        sa.Column("flight_id", sa.String(length=20), nullable=False),
        sa.Column("plate_number", sa.String(length=20), nullable=False),
        sa.Column("arrival_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("departure_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fuel_consumption", sa.Integer(), nullable=False),
        sa.Column("occupied_seats", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=100), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["plate_number"],
            ["airplanes.plate_number"],
        ),
        sa.PrimaryKeyConstraint("flight_id"),
    )
    op.create_table(
        "flight_passengers",
        sa.Column("flight_id", sa.String(length=20), nullable=False),
        sa.Column("passenger_id", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.flight_id"],
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.passenger_id"],
        ),
        sa.PrimaryKeyConstraint("flight_id", "passenger_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flight_passengers")
    op.drop_table("flights")
    op.drop_table("airplanes")
    op.drop_table("passengers")
    op.drop_table("hangars")
    # ### end Alembic commands ###
